import type { EcosystemContent } from "../ecosystem-types";

/**
 * Français — dossier écosystème mer Rouge (P0). Rédaction indépendante,
 * conforme au contrôle des affirmations et des preuves (ADR-015).
 */
export const frEcosystem: EcosystemContent = {
  hero: {
    eyebrow: "Écosystème économique et technologique",
    titleLines: [
      { text: "Structurer la production africaine,", emphasis: false },
      { text: "les chaînes d'approvisionnement de la mer Rouge", emphasis: true },
      { text: "et l'accès aux marchés via le Maroc.", emphasis: false },
    ],
    lead: "Akanil opère un écosystème économique et technologique reliant la production et les actifs du Soudan et de la Corne de l'Afrique aux ports de la mer Rouge, aux zones économiques, à la finance, à la technologie et aux capacités marocaines d'industrie et d'exportation.",
    primary: {
      label: "Trouvez votre point d'entrée",
      explanation: "Conduit aux parcours d'entrée ci-dessous.",
    },
    secondary: {
      label: "Explorer les plateformes du portefeuille",
      explanation: "Ouvre le portefeuille des plateformes opérées dans l'écosystème.",
    },
    institutional: {
      label: "Démarrer une demande structurée",
      explanation:
        "Ouvre le bureau d'accueil ; chaque demande est examinée par une équipe spécialisée.",
    },
  },
  whyRedSea: {
    title: "Pourquoi la mer Rouge ?",
    lead: "La mer Rouge n'est pas une simple route maritime. C'est l'espace économique où se rencontrent la production africaine, les ports, les zones économiques, l'industrie, la finance et l'accès aux marchés internationaux.",
    layersTitle: "Les couches qui se rencontrent sur la mer Rouge",
    layers: [
      "Production et ressources naturelles au Soudan et dans la Corne de l'Afrique",
      "Actifs agricoles, d'élevage, miniers et industriels",
      "Ports et nœuds logistiques",
      "Zones économiques et industrielles",
      "Capacités saoudiennes et égyptiennes d'industrie, d'investissement et de distribution",
      "Capacités marocaines d'industrie, de transformation, de normes et de qualité",
      "Institutions de financement du commerce, d'assurance et d'investissement",
      "Routes d'accès aux marchés internationaux via le Maroc et les ports de la mer Rouge",
      "Technologie, données, traçabilité et intelligence opérationnelle",
    ],
    bridgeTitle: "Le rôle distinctif d'Akanil",
    bridgeText:
      "Akanil comprend et structure le pont triangulaire reliant l'Afrique de l'Est, la mer Rouge et l'Arabie saoudite, puis connecte ce pont aux capacités industrielles, logistiques, financières et exportatrices du Maroc.",
    linkLabel: "Lire l'architecture du corridor de la mer Rouge",
  },
  valueFlow: {
    title: "Comment l'écosystème crée de la valeur",
    lead: "Une chaîne gouvernée unique, de la production et des actifs africains aux marchés régionaux et internationaux.",
    steps: [
      "Production et actifs africains",
      "Qualification et preuves",
      "Agrégation et transformation primaire",
      "Zones économiques et nœuds industriels",
      "Ports de la mer Rouge et corridors commerciaux",
      "Industrie, normes et finance",
      "Le Maroc, plateforme de transformation et d'accès aux marchés",
      "Marchés régionaux et internationaux",
    ],
    moroccoPlatformTitle: "Le Maroc comme plateforme — pas seulement un marché final",
    moroccoPlatformRoles: [
      "Transformation industrielle",
      "Transformation",
      "Conditionnement",
      "Normes et qualité",
      "Financement du commerce",
      "Assurance",
      "Logistique",
      "Distribution",
      "Préparation à l'exportation",
      "Accès aux marchés régionaux et internationaux",
    ],
    marketAccessNote:
      "Tout accès aux marchés européens, nord-américains, latino-américains ou ouest-africains demeure soumis aux règles d'origine applicables, aux exigences douanières, aux normes de produits, aux approbations réglementaires et au niveau de transformation réalisé.",
  },
  audiences: {
    eyebrow: "Entrer dans l'écosystème",
    title: "Choisissez votre rôle dans l'écosystème.",
    lead: "Sept parcours d'entrée institutionnels. Chacun conduit au bureau d'accueil avec le bon type de demande ; chaque demande est examinée par une équipe spécialisée.",
    whoLabel: "Qui est concerné",
    valueLabel: "Ce que la Passerelle apporte",
    platformsLabel: "Plateformes concernées",
    preparationLabel: "À préparer avant la demande",
    reviewOutputLabel: "Résultat attendu de la revue",
    paths: [
      {
        id: "moroccan-institutions",
        title: "Institutions marocaines",
        whoItIncludes: [
          "Institutions chargées de la coopération Sud–Sud",
          "Acteurs des affaires étrangères et de la coopération africaine",
          "Institutions économiques publiques et semi-publiques",
          "Associations d'exportateurs et corps professionnels",
          "Institutions de développement africaines et islamiques",
          "Agences d'investissement et de développement",
          "Institutions de formation et de recherche",
        ],
        strategicNeed:
          "Un instrument structuré et fondé sur les preuves pour la coopération économique avec le Soudan, la mer Rouge et la Corne de l'Afrique.",
        gatewayValue: [
          "Cadres de coopération structurés",
          "Dossiers économiques qualifiés",
          "Demande sectorielle documentée",
          "Visibilité sur l'investissement et les chaînes commerciales",
          "Accès contrôlé aux parties prenantes",
          "Revue des programmes et projets",
          "Suivi mesurable",
        ],
        relevantPlatforms: ["trade-chain-africa", "valura"],
        allowedRequestTypes: ["institutional-cooperation", "forum-qualification"],
        defaultRequestType: "institutional-cooperation",
        preparationRequirements: [
          "Identité institutionnelle et mandat",
          "Objet et périmètre de coopération envisagés",
        ],
        expectedReviewOutput:
          "Briefing institutionnel préliminaire et clarification du périmètre, avec identification des écarts de mandat ou de preuves.",
        ctaLabel: "Ouvrir une coopération institutionnelle",
      },
      {
        id: "moroccan-industry-exporters",
        title: "Industrie et exportateurs marocains",
        whoItIncludes: [
          "Énergies renouvelables et intrants agricoles",
          "Mines, agroalimentaire, conserverie et conditionnement",
          "Cosmétique, technologie, télécoms et e-commerce",
          "Logistique et chaîne du froid",
          "Importateurs de bétail et d'aliments du bétail",
          "Industriels cherchant des intrants africains bruts ou semi-transformés",
          "Exportateurs visant le Soudan et la Corne de l'Afrique",
        ],
        strategicNeed:
          "Structuration de l'entrée sur les marchés et accès à des parties prenantes qualifiées — pas une mise en relation ouverte.",
        gatewayValue: [
          "Nouveaux parcours d'entrée sur les marchés",
          "Demande qualifiée",
          "Dossiers structurés de fournisseurs et d'actifs",
          "Accès à la production soudanaise et de la Corne de l'Afrique",
          "Opportunités de partenariat industriel",
          "Scénarios logistiques mer Rouge",
          "Suivi institutionnel documenté",
        ],
        relevantPlatforms: ["rwafid", "trade-chain-africa", "valura"],
        allowedRequestTypes: [
          "market-expansion",
          "supply-offtake-requirement",
          "industrial-partnership",
          "forum-qualification",
        ],
        defaultRequestType: "market-expansion",
        preparationRequirements: [
          "Profil de l'entreprise et secteur",
          "Marché cible ou besoin d'approvisionnement",
        ],
        expectedReviewOutput:
          "Revue préliminaire de pertinence d'entrée sur le marché, catégories de parties prenantes requises et étape de qualification recommandée.",
        ctaLabel: "Structurer une entrée sur le marché",
      },
      {
        id: "moroccan-finance-investment",
        title: "Finance et investissement marocains",
        whoItIncludes: [
          "Banques de développement et banques commerciales",
          "Assureurs et financement du commerce",
          "Fonds d'investissement et institutions de garantie",
          "Conseillers financiers et acteurs de la finance islamique",
        ],
        strategicNeed:
          "Revue contrôlée de projets et structuration des besoins de financement le long du corridor.",
        gatewayValue: [
          "Visibilité contrôlée du portefeuille de projets",
          "Filtrage des projets et des actifs",
          "Analyse sectorielle et du corridor",
          "Besoins de financement structurés",
          "Parcours de due diligence",
          "Identification des risques et des écarts de preuves",
          "Accès à des porteurs de projets qualifiés",
        ],
        relevantPlatforms: ["valura", "ibriz-gaas", "trade-chain-africa"],
        allowedRequestTypes: [
          "project-investment-review",
          "institutional-cooperation",
          "forum-qualification",
        ],
        defaultRequestType: "project-investment-review",
        preparationRequirements: [
          "Profil de l'institution et axe de revue",
          "Secteur ou catégorie de projets d'intérêt",
        ],
        expectedReviewOutput:
          "Revue préliminaire d'adéquation du projet, exigences de preuves contrôlées et parcours de revue.",
        ctaLabel: "Demander une revue de projet",
        note: "La présence d'un projet sur ce site ne le rend pas bancable ; aucune disponibilité de financement n'est affirmée ni suggérée.",
      },
      {
        id: "sudanese-decision-makers",
        title: "Décideurs soudanais",
        whoItIncludes: [
          "Institutions économiques et autorités sectorielles",
          "Corps professionnels",
          "Décideurs du commerce et de l'investissement",
          "Organisations d'exportation et de production",
        ],
        strategicNeed:
          "Une coopération structurée avec les institutions, l'industrie, la finance et la technologie marocaines.",
        gatewayValue: [
          "Coopération structurée avec les institutions et industries marocaines",
          "Représentation des projets et des secteurs",
          "Parcours d'industrialisation",
          "Planification des normes et de l'accès aux marchés",
          "Coordination de l'investissement et de la technologie",
          "Décisions documentées et suivi",
        ],
        relevantPlatforms: ["valura", "rwafid", "trade-chain-africa"],
        allowedRequestTypes: [
          "institutional-cooperation",
          "industrial-partnership",
          "forum-qualification",
        ],
        defaultRequestType: "institutional-cooperation",
        preparationRequirements: [
          "Identité institutionnelle et autorité",
          "Objet de coopération ou axe sectoriel",
        ],
        expectedReviewOutput:
          "Briefing institutionnel préliminaire et parcours de coopération défini avec exigences de preuves.",
        ctaLabel: "Ouvrir une coopération institutionnelle",
        note: "Akanil ne représente pas le gouvernement soudanais.",
      },
      {
        id: "sudanese-producers-asset-owners",
        title: "Producteurs, exportateurs et détenteurs d'actifs soudanais",
        whoItIncludes: [
          "Exportateurs agricoles et d'aliments du bétail",
          "Sociétés minières et propriétaires de bétail",
          "Propriétaires de terres agricoles et d'usines",
          "Détenteurs d'actifs de stockage et de transformation",
          "Porteurs de projets",
        ],
        strategicNeed:
          "Structurer des actifs, produits et projets en dossiers qualifiés capables d'atteindre l'industrie, la finance et les marchés.",
        gatewayValue: [
          "Accès aux acheteurs et industriels marocains",
          "Parcours de transformation industrielle et montée en gamme",
          "Exigences de normes et de conditionnement",
          "Discussions de financement et d'assurance",
          "Scénarios de chaînes d'approvisionnement et de ports",
          "Évaluation de l'accès aux marchés internationaux via le Maroc",
          "Qualification des projets et des actifs",
        ],
        relevantPlatforms: ["rwafid", "valura", "trade-chain-africa"],
        allowedRequestTypes: [
          "submit-project-asset",
          "supply-offtake-requirement",
          "industrial-partnership",
          "forum-qualification",
        ],
        defaultRequestType: "submit-project-asset",
        preparationRequirements: [
          "Identification de l'actif, du produit ou du projet",
          "Preuves disponibles (profil, documents, études)",
        ],
        expectedReviewOutput:
          "Classification préliminaire, revue de complétude des preuves et décision sur l'ouverture d'une revue de projet contrôlée.",
        ctaLabel: "Soumettre un projet ou un actif",
        note: "Un produit brut n'acquiert pas automatiquement l'origine marocaine ni un traitement préférentiel à l'exportation.",
      },
      {
        id: "red-sea-ports-economic-zones",
        title: "Ports et zones économiques de la mer Rouge",
        whoItIncludes: [
          "Autorités portuaires et opérateurs de terminaux",
          "Développeurs de zones économiques et logistiques",
          "Acteurs du transport maritime et du stockage",
          "Opérateurs de zones industrielles",
          "Investisseurs régionaux",
        ],
        strategicNeed:
          "Visibilité des flux de production africains et rôles structurés dans le développement du corridor.",
        gatewayValue: [
          "Visibilité des flux de production africains",
          "Structuration potentielle des cargaisons et chaînes d'approvisionnement",
          "Liaison projets et zones",
          "Demande d'industrie et de transformation",
          "Développement du corridor Maroc–mer Rouge",
          "Coordination des parties prenantes",
          "Architecture technologique et de traçabilité",
        ],
        relevantPlatforms: ["trade-chain-africa", "valura"],
        allowedRequestTypes: [
          "port-logistics-cooperation",
          "institutional-cooperation",
        ],
        defaultRequestType: "port-logistics-cooperation",
        preparationRequirements: [
          "Profil de l'organisation et rôle opérationnel",
          "Corridor ou zone d'intérêt",
        ],
        expectedReviewOutput:
          "Évaluation préliminaire du rôle dans le corridor, besoins de données logistiques et parcours de plateforme pertinent.",
        ctaLabel: "Ouvrir une coopération corridor",
        note: "Aucun accord opérationnel n'est impliqué par ce parcours.",
      },
      {
        id: "technology-logistics-knowledge-partners",
        title: "Partenaires technologie, logistique et savoir",
        whoItIncludes: [
          "Sociétés technologiques et opérateurs télécoms",
          "Fournisseurs d'IA, d'infrastructures de données et de traçabilité",
          "Opérateurs logistiques et chaîne du froid",
          "Institutions de recherche et universités",
          "Organismes de formation, de normes et d'essais",
        ],
        strategicNeed:
          "Des rôles définis dans les couches technologique, logistique et de savoir de l'écosystème.",
        gatewayValue: [
          "Rôles définis dans l'écosystème",
          "Cas d'usage du portefeuille et des chaînes de valeur",
          "Opportunités de déploiement soumises à qualification",
          "Exigences techniques",
          "Intégration industrielle et logistique",
          "Parcours de coopération contrôlés",
        ],
        relevantPlatforms: ["ibriz-gaas", "trade-chain-africa", "rwafid"],
        allowedRequestTypes: [
          "technology-data-partnership",
          "industrial-partnership",
          "port-logistics-cooperation",
        ],
        defaultRequestType: "technology-data-partnership",
        preparationRequirements: [
          "Profil de capacités et cas d'usage de référence",
          "Rôle envisagé dans l'écosystème",
        ],
        expectedReviewOutput:
          "Évaluation préliminaire du rôle technique avec considérations d'intégration, de preuves et de gouvernance des données.",
        ctaLabel: "Présenter une capacité technologique",
      },
    ],
  },
  platforms: {
    eyebrow: "Plateformes du portefeuille",
    title: "Des plateformes stratégiques opérées dans l'écosystème.",
    lead: "Akanil gère un portefeuille contrôlé de plateformes qui structurent corridors commerciaux, zones économiques, chaînes d'approvisionnement et infrastructures technologiques réglementées.",
    categoryLabel: "Catégorie",
    purposeLabel: "Objet",
    problemLabel: "Problème traité",
    roleLabel: "Rôle d'Akanil",
    scopeLabel: "Géographies principales",
    audiencesLabel: "Audiences concernées",
    capabilitiesLabel: "Capacités",
    statusLabel: "Statut public",
    evidenceLabel: "État des preuves",
    regulatoryLabel: "Note réglementaire",
    items: [
      {
        id: "trade-chain-africa",
        name: "Trade-Chain Africa",
        category: "Ports, logistique et corridors commerciaux",
        purpose:
          "Plateforme de structuration de corridors commerciaux et de coordination des parties prenantes.",
        problemSolved:
          "La production africaine atteint la mer Rouge et les marchés internationaux par des routes fragmentées et non documentées, aux exigences de normes et de logistique incertaines.",
        operatingRole:
          "Akanil structure les scénarios de corridor, coordonne des parties prenantes qualifiées et documente les exigences de routes, de normes et de logistique.",
        geographicScope: [
          "King Abdullah Economic City et King Abdullah Port",
          "Aïn Sokhna",
          "Nœud économique et logistique d'Assouan",
          "Port-Soudan",
          "Bosaso",
          "Corridor économique et logistique Asmara–Massawa",
          "Tanger Med comme nœud marocain d'industrie et d'accès aux marchés",
        ],
        targetStakeholders: [
          "red-sea-ports-economic-zones",
          "moroccan-industry-exporters",
          "technology-logistics-knowledge-partners",
        ],
        capabilities: [
          "Structurer les routes commerciales et comparer les scénarios de corridor",
          "Relier les régions de production aux ports",
          "Organiser les exigences d'agrégation et d'expédition",
          "Identifier les besoins de chaîne du froid et de stockage",
          "Cartographier les exigences douanières, d'inspection et de normes",
          "Relier zones économiques, industries et marchés",
          "Appuyer des décisions logistiques et commerciales documentées",
        ],
        publicStatus: "structured-project",
        evidenceState: "controlled-evidence-available",
        cta: {
          label: "Discuter une coopération corridor",
          requestType: "port-logistics-cooperation",
        },
      },
      {
        id: "valura",
        name: "Projet Valura",
        category: "Développement de zones économiques et de valeur ajoutée",
        purpose:
          "Le modèle d'Akanil pour transformer des régions de production en nœuds économiques connectés.",
        problemSolved:
          "Les régions de production exportent brut, sans agrégation, essais, transformation, utilités ni liaison aux marchés — la valeur part avant d'être créée.",
        operatingRole:
          "Akanil structure des projets de zones combinant agrégation, tri, essais, stockage, transformation primaire, industrie, utilités, eau et énergie, logistique, infrastructure numérique, services industriels et liaison aux marchés.",
        geographicScope: [
          "État du Nord, Soudan",
          "État de Kassala",
          "État d'Al-Gedaref",
        ],
        targetStakeholders: [
          "sudanese-producers-asset-owners",
          "moroccan-finance-investment",
          "sudanese-decision-makers",
        ],
        capabilities: [
          "Agrégation, tri et essais",
          "Stockage et transformation primaire",
          "Industrie et services industriels",
          "Utilités, eau et énergie",
          "Logistique et infrastructure numérique",
          "Liaison aux marchés",
        ],
        publicStatus: "structured-project",
        evidenceState: "controlled-evidence-available",
        regulatoryNote:
          "Aucune zone économique n'est présentée comme établie, licenciée ou approuvée par un gouvernement ; les sites restent des projets de développement structurés, en revue institutionnelle, avec validation de site requise.",
        cta: {
          label: "Demander une revue de projet",
          requestType: "project-investment-review",
        },
      },
      {
        id: "rwafid",
        name: "RWAFID — روافد",
        category: "Chaînes d'approvisionnement cultures, aliments du bétail et élevage",
        purpose:
          "Plateforme de structuration, de qualification et d'accès aux marchés des chaînes d'approvisionnement.",
        problemSolved:
          "Cultures, aliments du bétail et cheptel circulent en flux bruts non documentés, perdant une valeur qui pourrait être créée à la source, en zone africaine, sur un nœud mer Rouge, en Arabie saoudite, en Égypte ou au Maroc.",
        operatingRole:
          "Akanil structure et qualifie les chaînes agricoles et d'élevage — céréales, sésame, arachide, oléagineux, fourrages, concentrés et intrants ; animaux vivants avec exigences vétérinaires, traçabilité, quarantaine, transport, chaîne du froid, abattage et sous-produits.",
        geographicScope: [
          "Régions de production soudanaises",
          "Nœuds industriels de la mer Rouge",
          "Arabie saoudite et Égypte",
          "Maroc",
        ],
        targetStakeholders: [
          "sudanese-producers-asset-owners",
          "moroccan-industry-exporters",
          "sudanese-decision-makers",
        ],
        capabilities: [
          "Structuration des chaînes de cultures et d'aliments du bétail",
          "Chaînes d'élevage avec exigences vétérinaires et de quarantaine",
          "Planification de la traçabilité et de la chaîne du froid",
          "Création de valeur à la source, en zone, sur un nœud ou à destination",
          "Préparation des normes, du conditionnement et de l'accès aux marchés",
        ],
        publicStatus: "structured-project",
        evidenceState: "controlled-evidence-available",
        cta: {
          label: "Structurer un besoin d'approvisionnement",
          requestType: "supply-offtake-requirement",
        },
      },
      {
        id: "ibriz-gaas",
        name: "IBRIZ et GAAS",
        category: "Technologie financière et infrastructure bancaire",
        purpose:
          "IBRIZ — projet d'infrastructure numérique de l'or et de banque. GAAS — Gold as a Service pour institutions financières réglementées.",
        problemSolved:
          "Les institutions réglementées manquent d'infrastructures conformes et traçables pour la valeur numérique adossée à l'or.",
        operatingRole:
          "Akanil développe l'architecture produit envisagée : infrastructure de comptes numériques adossés à l'or, représentation de valeur adossée à des actifs, traçabilité des transactions, infrastructure orientée conformité, modules d'intégration bancaire et capacités GAAS pour banques et institutions réglementées.",
        geographicScope: ["Déploiements institutionnels réglementés"],
        targetStakeholders: [
          "technology-logistics-knowledge-partners",
          "moroccan-finance-investment",
        ],
        capabilities: [
          "Infrastructure de comptes numériques adossés à l'or",
          "Représentation de valeur adossée à des actifs",
          "Traçabilité des transactions",
          "Infrastructure orientée conformité",
          "Modules d'intégration bancaire",
          "GAAS pour institutions réglementées",
        ],
        publicStatus: "regulated-development",
        evidenceState: "evidence-restricted",
        regulatoryNote:
          "IBRIZ et GAAS sont présentés comme des projets de technologie financière et d'infrastructure bancaire. Toute activité réglementée de banque, de paiement, de conservation, d'investissement ou de comptes adossés à l'or demeure soumise aux licences applicables, aux approbations réglementaires et aux accords de déploiement institutionnel.",
        cta: {
          label: "Discuter l'infrastructure réglementée",
          requestType: "technology-data-partnership",
        },
      },
    ],
  },
  nodes: {
    eyebrow: "Nœuds de la mer Rouge",
    title: "Architecture de l'écosystème et du corridor.",
    lead: "Une architecture schématique des ports, régions de production, zones économiques et nœuds d'accès aux marchés que l'écosystème relie — non une carte de routes juridique ou technique.",
    mapLabel: "Diagramme schématique de l'architecture de l'écosystème et du corridor",
    disclaimer:
      "Architecture schématique uniquement. Aucune route, aucun volume, temps de trajet, coût ou capacité n'est présenté comme vérifié ; chaque scénario exige une vérification commerciale, logistique et réglementaire actuelle.",
    kindLabels: {
      port: "Port",
      "economic-zone": "Zone économique",
      "industrial-node": "Nœud industriel",
      "production-region": "Région de production",
      "logistics-node": "Nœud logistique",
      "market-access-node": "Nœud d'accès aux marchés",
      "financial-node": "Nœud financier",
    },
    listTitle: "Nœuds de l'écosystème",
    selectPrompt: "Sélectionnez un nœud pour lire son rôle dans l'architecture.",
    items: [
      {
        id: "tanger-med",
        name: "Tanger Med",
        country: "Maroc",
        kind: "port",
        role: "Port marocain et écosystème industriel et logistique connecté",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Le complexe portuaire phare du Maroc et son écosystème industriel et logistique, référencé comme nœud d'accès aux marchés dans les scénarios de corridor.",
        evidenceState: "public-summary-available",
        publicStatus: "public-profile",
      },
      {
        id: "morocco-industry",
        name: "Industrie et transformation marocaines",
        country: "Maroc",
        kind: "industrial-node",
        role: "Capacités de transformation industrielle",
        platformIds: ["rwafid", "trade-chain-africa"],
        publicSummary:
          "Capacités d'industrie, de transformation, de conditionnement et de production sous contrat qui élèvent la valeur des intrants africains qualifiés.",
        evidenceState: "public-summary-available",
        publicStatus: "public-profile",
      },
      {
        id: "morocco-finance",
        name: "Finance et assurance marocaines",
        country: "Maroc",
        kind: "financial-node",
        role: "Fonctions de financement du commerce, d'assurance et d'investissement",
        platformIds: ["trade-chain-africa", "ibriz-gaas"],
        publicSummary:
          "Fonctions bancaires, assurantielles et de conseil qui structurent paiement, couverture et financement autour d'interlocuteurs documentés.",
        evidenceState: "public-summary-available",
        publicStatus: "public-profile",
      },
      {
        id: "morocco-market-access",
        name: "Normes et fonctions d'exportation marocaines",
        country: "Maroc",
        kind: "market-access-node",
        role: "Normes, qualité et préparation de l'accès aux marchés",
        platformIds: ["trade-chain-africa", "rwafid"],
        publicSummary:
          "Fonctions de normes, de qualité, de certification et de préparation à l'exportation vers les marchés régionaux et internationaux, sous réserve des règles d'origine, des exigences douanières et du niveau de transformation.",
        evidenceState: "public-summary-available",
        publicStatus: "public-profile",
      },
      {
        id: "kaec",
        name: "King Abdullah Economic City",
        country: "Arabie saoudite",
        kind: "economic-zone",
        role: "Ville économique et nœud industriel saoudien",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Ville économique saoudienne référencée dans les scénarios de corridor pour l'industrie, l'investissement et la distribution.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
      {
        id: "king-abdullah-port",
        name: "King Abdullah Port",
        country: "Arabie saoudite",
        kind: "port",
        role: "Nœud portuaire saoudien de la mer Rouge",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Port saoudien de la mer Rouge référencé dans les scénarios reliant la production africaine aux marchés du Golfe.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
      {
        id: "ain-sokhna",
        name: "Aïn Sokhna",
        country: "Égypte",
        kind: "port",
        role: "Port égyptien et nœud économique et industriel",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Port égyptien de la mer Rouge et nœud économique et industriel, cité pour les scénarios de transit, de stockage et de transformation.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
      {
        id: "aswan",
        name: "Assouan",
        country: "Égypte",
        kind: "logistics-node",
        role: "Nœud intérieur économique, productif et logistique",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Nœud égyptien intérieur pour des fonctions économiques, productives et logistiques sur l'axe du Nil — ce n'est pas un port maritime.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
      {
        id: "port-sudan",
        name: "Port-Soudan",
        country: "Soudan",
        kind: "port",
        role: "Principal port soudanais de la mer Rouge",
        platformIds: ["trade-chain-africa", "rwafid"],
        publicSummary:
          "La principale porte maritime du Soudan sur la mer Rouge dans les scénarios reliant régions de production et marchés.",
        evidenceState: "controlled-evidence-available",
        publicStatus: "structured-project",
      },
      {
        id: "northern-state",
        name: "État du Nord",
        country: "Soudan",
        kind: "production-region",
        role: "Zones de production agricoles et économiques",
        platformIds: ["valura", "rwafid"],
        publicSummary:
          "Zones agricoles et économiques traitées par le modèle de développement de zones Valura.",
        evidenceState: "controlled-evidence-available",
        publicStatus: "structured-project",
      },
      {
        id: "kassala",
        name: "Kassala",
        country: "Soudan",
        kind: "production-region",
        role: "Zones de production agricole et d'élevage",
        platformIds: ["valura", "rwafid"],
        publicSummary:
          "Zones orientales de cultures et d'élevage, reliées à la logistique de la mer Rouge par les scénarios de corridor.",
        evidenceState: "controlled-evidence-available",
        publicStatus: "structured-project",
      },
      {
        id: "gedaref",
        name: "Al-Gedaref",
        country: "Soudan",
        kind: "production-region",
        role: "Zones de production de céréales et d'oléagineux",
        platformIds: ["valura", "rwafid"],
        publicSummary:
          "L'une des principales régions céréalières et oléagineuses du Soudan, traitée par les scénarios d'agrégation, de transformation et de liaison aux marchés.",
        evidenceState: "controlled-evidence-available",
        publicStatus: "structured-project",
      },
      {
        id: "asmara-massawa",
        name: "Corridor économique et logistique Asmara–Massawa",
        country: "Érythrée",
        kind: "logistics-node",
        role: "Corridor économique et logistique de l'intérieur vers la côte",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Le corridor reliant Asmara, à l'intérieur, à la côte à Massawa, référencé comme scénario logistique de la Corne de l'Afrique en attente de documentation contrôlée.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
      {
        id: "bosaso",
        name: "Port de Bosaso",
        country: "Puntland, Somalie",
        kind: "port",
        role: "Nœud portuaire de la Corne de l'Afrique",
        platformIds: ["trade-chain-africa"],
        publicSummary:
          "Port de la Corne de l'Afrique référencé dans les scénarios de flux de bétail et de commerce vers le Golfe.",
        evidenceState: "evidence-not-yet-published",
        publicStatus: "institutional-review",
      },
    ],
  },
  technology: {
    eyebrow: "Technologie et intelligence opérationnelle",
    title: "La technologie organise les preuves. Les spécialistes décident.",
    lead: "L'écosystème est conçu autour des preuves, de la traçabilité et d'une intelligence soumise à revue humaine — la technologie est une couche opérationnelle, pas un décor.",
    principle:
      "La technologie organise les preuves et propose l'analyse. Les spécialistes autorisés examinent et décident.",
    stateLabel: "État",
    capabilities: [
      {
        title: "Fenêtre publique et accueil par email",
        text: "Ce site trilingue et le bureau d'accueil structuré par email.",
        state: "active-public",
      },
      {
        title: "Revue spécialisée des demandes",
        text: "Classification et revue des demandes institutionnelles par l'équipe pluridisciplinaire.",
        state: "manual-specialist-review",
      },
      {
        title: "Registres des parties prenantes",
        text: "Dossiers structurés des organisations, rôles et consentements.",
        state: "planned",
      },
      {
        title: "Dossiers de projets et d'actifs avec évaluation des preuves",
        text: "Passeports de projets, attribution des sources et évaluation de complétude.",
        state: "planned",
      },
      {
        title: "Traçabilité des chaînes et analyse de scénarios d'itinéraires",
        text: "Analyse des chaînes commerciales reliant production, nœuds, ports et marchés.",
        state: "prototype",
      },
      {
        title: "Comptes rendus de réunions, décisions et engagements",
        text: "Réunions, décisions et engagements documentés avec suivi.",
        state: "planned",
      },
      {
        title: "Data rooms contrôlées",
        text: "Accès classifié aux documents pour les interlocuteurs autorisés, dans des phases ultérieures.",
        state: "planned",
      },
      {
        title: "Assistance IA sous revue humaine",
        text: "Classification et contrôles de complétude assistés par IA, sous revue spécialisée.",
        state: "manual-specialist-review",
      },
      {
        title: "Infrastructure bancaire réglementée (IBRIZ / GAAS)",
        text: "Technologie institutionnelle liée à l'or, soumise aux licences et approbations réglementaires.",
        state: "regulated",
      },
    ],
  },
  review: {
    eyebrow: "Revue spécialisée",
    title: "Chaque demande est examinée par une équipe spécialisée.",
    lead: "Les demandes institutionnelles sont examinées par une équipe pluridisciplinaire autorisée, selon le sujet, le secteur et les preuves fournies. Chaque discipline n'examine pas chaque demande.",
    disciplinesTitle: "Disciplines de revue",
    disciplines: [
      "Développement institutionnel et des affaires",
      "Commerce international",
      "Chaînes d'approvisionnement et logistique",
      "Juridique et conformité",
      "Finance et investissement",
      "Agriculture et élevage",
      "Mines et industrie",
      "Technologie et données",
      "Gestion des projets et des preuves",
    ],
    routingTitle: "Comment circule une demande",
    routing: [
      "Accueil",
      "Classification de l'audience et de la demande",
      "Contrôle du minimum d'informations",
      "Revue spécialisée pertinente",
      "Identification des écarts de preuves",
      "Prochaine étape recommandée",
    ],
    guarantees: [
      "La réception ne vaut pas acceptation.",
      "La revue ne vaut pas endossement.",
      "Des informations complémentaires peuvent être demandées.",
      "Seuls des humains autorisés déterminent la prochaine étape.",
      "L'IA peut assister la classification ou les contrôles de complétude mais n'approuve aucune demande.",
    ],
  },
  states: {
    publicStatus: {
      "public-profile": "Profil public",
      "structured-project": "Projet de développement structuré",
      "controlled-review-available": "Revue contrôlée disponible",
      "institutional-review": "En revue institutionnelle",
      "technical-development": "En développement technique",
      "regulated-development": "Développement réglementé",
      "not-publicly-active": "Non actif publiquement",
    },
    evidenceState: {
      "public-summary-available": "Résumé public disponible",
      "controlled-evidence-available": "Revue de preuves contrôlée",
      "due-diligence-summary-available": "Revue de due diligence contrôlée disponible",
      "evidence-update-required": "Mise à jour des preuves requise",
      "evidence-restricted": "Preuves restreintes",
      "evidence-not-yet-published": "Preuves non encore publiées",
    },
    capabilityState: {
      "active-public": "Actif — public",
      "active-controlled": "Actif — contrôlé",
      "manual-specialist-review": "Revue spécialisée manuelle",
      prototype: "Prototype",
      planned: "Planifié",
      regulated: "Soumis à réglementation",
    },
  },
  claims: {
    title: "Portée publique de ce site",
    scope: [
      "Les rôles décrits ici sont des rôles d'écosystème et de développement de projets ; ils n'impliquent aucun partenariat avec des institutions, ports ou zones nommés.",
      "Aucune route n'est opérationnellement vérifiée du seul fait de figurer dans un diagramme.",
      "Aucun projet n'est prêt à l'investissement ni bancable du seul fait de sa publication ; la revue de projet est contrôlée et fondée sur les preuves.",
      "Aucune licence, approbation gouvernementale ou création de zone économique n'est revendiquée sans preuve documentaire.",
      "Aucun produit financier réglementé n'est proposé ; IBRIZ et GAAS restent soumis aux licences et approbations réglementaires.",
      "Akanil n'approuve pas seule l'investissement, le financement, les licences, la conformité aux normes ni les décisions gouvernementales.",
    ],
  },
  founder: {
    name: "Mohamed Abderrahim",
    bridgeTitle: "Un pont bâti depuis les deux rives",
    bridgeText:
      "L'expérience professionnelle et institutionnelle du fondateur couvre à la fois les écosystèmes d'exportation marocain et soudanais, fondant le rôle d'Akanil comme fondateur et opérateur exécutif de l'écosystème — l'opérateur qui structure le pont entre l'Afrique de l'Est, la mer Rouge, l'Arabie saoudite et le Maroc.",
  },
  portfolioPage: {
    title: "Plateformes du portefeuille — Passerelle économique Akanil Maroc–mer Rouge",
    description:
      "Le portefeuille contrôlé des plateformes opérées dans l'écosystème : Trade-Chain Africa, Valura, RWAFID et IBRIZ/GAAS.",
    heading: "Plateformes du portefeuille",
    lead: "Des plateformes stratégiques opérées, développées ou structurées dans l'écosystème — chacune avec un statut public et un état des preuves explicites.",
  },
  corridorPage: {
    heading: "L'architecture des chaînes d'approvisionnement de la mer Rouge",
    lead: "Régions de production et d'actifs, ports, nœuds économiques et industriels, rôle de transformation du Maroc et conception d'itinéraires par scénarios — sous des règles explicites de preuves et de vérification.",
    scenariosTitle: "Conception d'itinéraires par scénarios",
    rulesTitle: "Règles de preuves et de vérification",
    rules: [
      "Chaque scénario d'itinéraire porte un état textuel explicite ; rien n'est vérifié par sa seule apparition.",
      "Les dépendances réglementaires, douanières et logistiques sont évaluées par scénario.",
      "Aucun temps de trajet, volume, coût ou capacité n'est publié sans preuve actuelle.",
      "La direction géographique est préservée dans toutes les langues ; le diagramme est schématique.",
    ],
  },
  ui: {
    navPortfolio: "Portefeuille",
    footerPortfolio: "Plateformes du portefeuille",
    learnMoreWhyRedSea: "Pourquoi la mer Rouge ?",
  },
};
